### ISSUE TITLE
Image/Video sourceType not working as expected

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#18]
https://github.com/jeromeetienne/AR.js/issues/593

**Comment by kalwalt** [comment]
@jonasjohnsson probably you have this issue because are you trying this on Glitch and the canvas i tainted? Are you receiving this kind of error in the console?

```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at ARController._copyImageToHeap (https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:1046:28)
    at ARController.detectMarker (https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:518:12)
    at ARController.process (https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:139:8)
    at ARjs.Context.THREEx.ArToolkitContext.ARjs.Context._updateArtoolkit (https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:2683:23)
    at ARjs.Context.THREEx.ArToolkitContext.ARjs.Context.update (https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:2556:14)
    at ARjs.Session.update (https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:4025:13)
    at o.tick (https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:5996:25)
    at HTMLElement.tick (https://cdn.jsdelivr.net/gh/aframevr/aframe@1c2407b26c61958baa93967b5412487cd94b290b/dist/aframe-master.min.js:941:11947)
    at HTMLElement.render (https://cdn.jsdelivr.net/gh/aframevr/aframe@1c2407b26c61958baa93967b5412487cd94b290b/dist/aframe-master.min.js:941:12381)
    at https://cdn.jsdelivr.net/gh/aframevr/aframe@1c2407b26c61958baa93967b5412487cd94b290b/dist/aframe-master.min.js:1072:132
```
you can check this my [codepen](https://codepen.io/kalwalt/pen/JjdejBJ) and you will get that error. In localhost and other env i'm sure that it is working ( i will provide a link when i have time).

**Comment by kalwalt** [comment]
It works for me see this link: https://kalwalt.github.io/kalwalt-interactivity-AR/arjs/default-thinner-border.html
