### ISSUE TITLE
Failures in AR js and Printed Images

### ISSUE THREAD

**Issue by Jorg313** [AR-js-org/AR.js#314]
I have two problems with AR JS.
Firstly my Programm throws the following errors when using ar.js:
Failed to load resource: the server responded with a status of 404 ()
aframe-ar.js:2 Pattern Data read error!!
aframe-ar.js:2 loadMarker(): Error loading pattern file /marker_0.
aframe-ar.js:2 ARToolKitJS(): Unable to set up AR marker.
OBJLoader.js:786 OBJLoader: 58.755859375 ms
aframe-ar.js:2 Out of memory!!
aframe-ar.js:19 Uncaught ExitStatusmessage: "Program terminated with exit(1)"name: "ExitStatus"status: 1__proto__: Error
    at https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:19:2247constructor: ƒ ExitStatus(status)stack: "Error\n    at https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js:19:2247"__proto__: constructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()__proto__: Object

(The code is found in: https://github.com/Jorg313/ARJStest1/Test1.html)

The other problem is that AR js doesnt seem to even recognize its markers. I have printed out multiple Hiro Markers and also used the examples from the website, but the programm seems to not recognize them. Is there a problem AR.js or is there a way to make the markers more easily recognizable?

**Comment by kalwalt** [comment]
Sorry for the delay @Jorg313 but you should at least fill the issue with all the infos required and also the resource you posted is unvailable.
