### ISSUE TITLE
When running the A-Frame location-based sample code in React, errors occur.

### ISSUE THREAD

**Issue by Hyeonoo-Park** [AR-js-org/AR.js#515]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

I am developing based on the A-Frame location based sample code using React, but I am getting an error when I run it on the device. I am not familiar with web programming, so I am not sure if this is a bug or if I am doing something wrong. To resolve the issue, I received the AR.js source and made a few modifications and now it works without errors.

The errors are:

- THREEx is not defined
  ![image](https://user-images.githubusercontent.com/100818317/217186180-f7b3d277-88a5-4004-b6f7-4a9987dc0270.png)
-  Math.radToDeg, Math.degToRad
  ![image](https://user-images.githubusercontent.com/100818317/217186253-3b4cb8e6-9a7d-4a26-9450-98b4a6b3da18.png)

The development environment and source are as follows:
- ![image](https://user-images.githubusercontent.com/100818317/217186301-491e82e2-ef49-4cd8-8441-b9555ceac37d.png)
-  ![image](https://user-images.githubusercontent.com/100818317/217186363-36e609ad-2dbd-4089-b6da-42292c93fa18.png)

Environment set up with Webpack following the guide on the AR.js home page in React.
- List of packages used.
  ![image](https://user-images.githubusercontent.com/100818317/217187091-e99f1ff2-2057-4f50-852c-da2dbbc84f2f.png)
- Source code sample that causes the error.
  ![image](https://user-images.githubusercontent.com/100818317/217186743-1b8a7521-3b2e-4c19-9589-967ef390383c.png)

Modifications to the AR.js source:

- Changed "import { Math as MathUtils } from "three"" to "import { Math as MathUtils } from "three""
- ![image](https://user-images.githubusercontent.com/100818317/217187420-981f7581-4c69-4b88-8cb4-52a25dc73a06.png)
- Changed "THREE.Math" to "THREE.MathUtils"
- ![image](https://user-images.githubusercontent.com/100818317/217187557-69fb6197-20fb-4c6e-a72a-854d606de783.png)
  - Affected code is listed in the following list:
    - AR.js/aframe/dist/main.js
    - AR.js/three.js/src/threex/threex-arvideoinwebgl.js
    - AR.js/three.js/src/location-based/js/location-based.js
    - AR.js/three.js/src/location-based/js/lb.js
    - AR.js/aframe/src/location-based/gps-projected-camera.js
    - AR.js/aframe/src/location-based/gps-camera.js
    - AR.js/aframe/src/new-location-based/gps-new-entity-place.js
    - AR.js/aframe/src/location-based/ArjsDeviceOrientationControls.js

I hope to confirm whether this is a bug and incorporate it into an update.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nickw1** [comment]
Not sure what the problem is but will try and investigate it.
Do you use create-react-app or write your own build script? If the latter, do you have your package.json?

**Comment by Hyeonoo-Park** [comment]
> 

"I am using a project created using 'Create React App.

**Comment by nickw1** [comment]
Thanks - will take a look if I have a moment.

**Comment by miqmago** [comment]
This is happening to me also with the three.js location based example.
When using the A-Frame location based example it does not happen:

```
ar-threex-location-only.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'degToRad')
    at i._haversineDist (ar-threex-location-only.js:1:3291)
    at i._gpsReceived (ar-threex-location-only.js:1:2957)
    at ar-threex-location-only.js:1:1989
```

**Comment by nickw1** [comment]
Strange, I don't get that with the three location-based example but will have a look.

**Comment by miqmago** [comment]
I've created a gist with the code:

https://gist.github.com/miqmago/e1430405b34d384dec5fd393d6ee3ded

This is meant to be useed in a stencil 3.0.1 component.

**Comment by GordonSmith** [comment]
FYI - I am getting this also - but only on my mobile device, the browser on my PC works...

**Comment by nickw1** [comment]
@Hyeonoo-Park it looks like you have made additional changes, additional to those in @GordonSmith's PR.
Do you want to submit a PR for your other changes?

**Comment by Hyeonoo-Park** [comment]
The same problem occurs in v3.4.4.
I made a sample project and submitted a PR for the code I modified.

https://github.com/Hyeonoo-Park/react-ar-js-test

**Comment by kalwalt** [comment]
@Hyeonoo-Park i merged the fix for MathUtils from #523 #532 in the master branch now, It should be fine but can you test and tell me if it is ok?

**Comment by Hyeonoo-Park** [comment]
> 

"I'm sorry, it still hasn't been fixed. To run the React A-Frame code without errors, you need to add the following code to arjs-device-orientation-control.js."

Error!
![image](https://user-images.githubusercontent.com/100818317/230570749-db56b725-82a5-49b1-b211-647cb1e7b75f.png)

Fix:  arjs-device-orientation-controls.js
```
import * as THREEx from "../../../three.js/build/ar-threex-location-only.js";
```

This is the entry code for a React component that uses A-Frame.
```
import React from "react";
import "@ar-js-org/ar.js/aframe/build/aframe-ar";
import "../components/avatar/a-character-gps";

import modelAvatar from "../avatar/svravatar.json";

function ArLBSAFrame() {
  return (
    <a-scene vr-mode-ui="enabled: false;" renderer="antialias: true; alpha: true" arjs='sourceType: webcam; videoTexture: false; debugUIEnabled: false'>
    <a-camera gps-new-camera='gpsMinDistance: 5'></a-camera>
    <a-entity id='character-gps' character-gps={JSON.stringify(modelAvatar)}  gps-new-entity-place="longitude: 100, latitude: 30"></a-entity>
    </a-scene>
  );
}

export default ArLBSAFrame;
```

**Comment by jywarren** [comment]
Hi, I got the same error `THREEx is not defined` with a similar setup and am not using three.js, just a-frame. I will try to adapt the solution `import * as THREEx from "../../../three.js/build/ar-threex-location-only.js";` by also including that file... but that seems like it shouldn't be necessary? 

full error: https://gist.github.com/jywarren/c3f0670903e0595f1f37ae33be202837

which I believe leads to this line:

https://github.com/AR-js-org/AR.js/blob/e2f2893a7e0af8853687d34ca0aee7edf5321e9b/aframe/src/new-location-based/arjs-device-orientation-controls.js#L25

Shouldn't it be possible to not use any threejs code? Thank you!

**Comment by jywarren** [comment]
Also, including the same file just above the aframe script worked for me:

```
     <script src="https://raw.githack.com/AR-js-org/AR.js/master/three.js/build/ar-threex-location-only.js">
     <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js">
```

**Comment by sey323** [comment]
I was using Nuxt3 and had the same problem, but I solved it by specifying version 3.4.5 with reference to the following ISSUE.

https://github.com/AR-js-org/AR.js/issues/538#issuecomment-1544316282

```html
<script type="text/javascript" src="https://aframe.io/releases/1.6.0/aframe.min.js" ></script>
<script type="text/javascript" src="https://www.unpkg.com/@ar-js-org/ar.js@3.4.5/three.js/build/ar-threex-location-only.js" ></script>
<script type="text/javascript" src="https://www.unpkg.com/@ar-js-org/ar.js@3.4.5/aframe/build/aframe-ar.js"></script>
```

**Comment by nickw1** [comment]
@jywarren not sure if this is what you meant by "Shouldn't it be possible to not use any threejs code?" but the current A-Frame location-based code uses functionality from the three.js location-based code to avoid code duplication.

PR #563 might fix it, I haven't had time to work on AR.js for a while but might get the chance to test it.

**Comment by nickw1** [comment]
This is also discussed in #538, try downgrading to 3.4.4.
