### ISSUE TITLE
aframe-ar-nft.js report error

### ISSUE THREAD

**Issue by crithes** [AR-js-org/AR.js#540]
report error：Uncaught TypeError: Cannot read properties of undefined (reading 'degToRad')
    /WebARDemo/argis/js/aframe-ar-nft.js:1:1630531
TypeError: Cannot read properties of undefined (reading 'degToRad')
    at i._haversineDist (http://localhost:63342/WebARDemo/argis/js/aframe-ar-nft.js:1:1630531)
    at i.<anonymous> (http://localhost:63342/WebARDemo/argis/js/aframe-ar-nft.js:1:1627408)

**Comment by malejogs** [comment]
look at this https://github.com/AR-js-org/AR.js/issues/538
